import './globals.css'
import NavBar from './navbar';
import Profile from './profile';

export const metadata = {
  title: "Chin Lun Wong",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <NavBar/>
    </html>
  );
}
