import './globals.css'
import NavBar from './navbar';
import Profile from './profile';
import About from './about';
import { poppins } from "./fonts/fonts";

export const metadata = {
  title: "Chin Lun Wong",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavBar/>
        <Profile/>
        <About/>
      </body>
    </html>
  );
}
